package util

import java.io.File
import java.io.FileOutputStream
import java.io.PrintStream

/**
 * Created by Aedan Smith.
 */

fun File.write(string: String, func: PrintStream.() -> Unit) {
    val file = File(this, "$string.qz")
    file.createNewFile()
    val printStream = PrintStream(FileOutputStream(file))
    printStream.comment("This file was auto-generated by StdGen.kt; do not edit")
    func(printStream)
}

fun PrintStream.struct(name: String, vararg members: Pair<Pair<Boolean, String>, String>) {
    println("struct $name {")
    members.forEach {
        println("    ${if (it.first.first) "var" else "val"} ${it.first.second}: ${it.second}")
    }
    println("}")
}

fun PrintStream.externTypealias(name: String, type: String) {
    println("extern typealias $name = $type")
}

fun PrintStream.externFunction(name: String, ret: String?, vararg types: String) {
    println("extern fn $name${types.joinToString(prefix = "(", postfix = ")")}${if (ret != null) ": $ret" else ""}")
}

fun PrintStream.externVal(name: String, type: String) {
    println("fn get_$name(): $type { return %%$name%%; }")
}

fun PrintStream.externVar(name: String, type: String) {
    externVal(name, type)
    println("fn set_$name(value: $type) { %%$name = value%%; }")
}

fun PrintStream.include(string: String) {
    inlineC { print("\n#include <$string>\n") }
}

fun PrintStream.import(string: String) {
    println("import $string")
}

fun PrintStream.inlineC(func: PrintStream.() -> Unit) {
    print("%%")
    func(this)
    println("%%")
}

fun PrintStream.comment(string: String) {
    println("/* $string */")
}

fun PrintStream.todo(string: String) {
    println("// TODO $string")
}

fun PrintStream.newline() {
    println()
}
