/* Generated by the Quartz compiler */

int main();
void print(char* msg);

#include <stdio.h>

int main(){
    char* helloWorld = "Hello, World!";
    print(helloWorld);
    return 0;
}

void print(char* msg){
    printf(msg);
}
