/* Generated by the Quartz compiler */

int main();
char* helloWorld();
void print(char* msg);

#include <stdio.h>

int main(){
    print(helloWorld());
    return 0;
}

char* helloWorld(){
    return "Hello, World!";
}

void print(char* msg){
    printf(msg);
}
