/* Generated by Quartz compiler */

int main();
void print(char* msg);

int main() {
    char* helloWorld = "Hello, World!";
    print(helloWorld);
    return 0;
}

void print(char* msg) {
    printf(msg);
}
