/* Generated by Quartz compiler */

int main();
double add(double d1, double d2);
double sub(double d1, double d2);
double mlt(double d1, double d2);
double div(double d1, double d2);

int main() {
    double added = add((double) (1), (double) (2));
    double subtracted = sub((double) (2), (double) (1));
    double multiplied = mlt(added, subtracted);
    double divided = div(subtracted, added);
    return 0;
}

double add(double d1, double d2) {
    return (double) (d1 + d2);
}

double sub(double d1, double d2) {
    return (double) (d1 - d2);
}

double mlt(double d1, double d2) {
    return (double) (d1 * d2);
}

double div(double d1, double d2) {
    return (double) (d1 / d2);
}
