/* Generated by Quartz compiler */

int main();
double addFour(char one, short two, int three, long four);
long add(short one, int two);

int main() {
    long one = (long) (1);
    int two = 2;
    short three = (short) (3);
    char four = (char) (4);
    double result = addFour((char) (one), (short) (two), (int) (three), (long) (four));
    return 0;
}

double addFour(char one, short two, int three, long four) {
    return (double) (add((short) (add((short) (one), (int) (four))), (int) (add((short) (three), (int) (two)))));
}

long add(short one, int two) {
    return (long) (one + two);
}
