package quartz.compiler.generator

import quartz.compiler.generator.semantics.unwrapExpressions
import quartz.compiler.generator.semantics.verifyNames
import quartz.compiler.syntax.tree.ProgramNode
import quartz.compiler.visitor.plus

/**
 * Created by Aedan Smith.
 */

object Generator {
    fun generate(programNode: ProgramNode): String {
        val string = StringBuilder()
        ((ProgramNode::unwrapExpressions + ProgramNode::verifyNames)
                (programNode)).visit(string)
        return "/* Generated by the Quartz compiler */\n\n" + string.toString()
    }
}
