package quartz.compiler.generator

import quartz.compiler.generator.visitors.ProgramVisitor
import quartz.compiler.tree.ProgramNode

/**
 * Created by Aedan Smith.
 */

class Generator(val programVisitor: ProgramVisitor = ProgramVisitor()) {
    fun generate(programNode: ProgramNode): String {
        val string = StringBuilder()
        string.appendln("/* Generated by the Quartz compiler */")
        string.appendln()
        programVisitor(programNode, string, 0)
        return string.toString()
    }
}
