package quartz.compiler.generator

import java.io.OutputStream
import java.io.PrintStream

/**
 * Created by Aedan Smith.
 */

class ProgramOutputStream(outputStream: OutputStream) {
    private val identifierChars = { c: Char -> c in 'a'..'z' || c in 'A'..'Z' || c in '0'..'9'|| c == '_' }
    private var lastChar = ' '
    private var indent = 0
    val printStream = PrintStream(outputStream)

    init {
        comment("Generated by the Quartz compiler")
    }

    fun margin(function: ProgramOutputStream.() -> Unit) {
        newline()
        function()
        newline()
    }

    fun nbraces(function: ProgramOutputStream.() -> Unit) {
        braces {
            newline()
            function()
        }
    }

    fun braces(function: ProgramOutputStream.() -> Unit) {
        string("{")
        indent++
        function()
        indent--
        newline()
        string("}")
    }

    fun parentheses(function: ProgramOutputStream.() -> Unit) {
        string("(")
        function()
        string(")")
    }

    fun comment(string: String) {
        string("/* $string */\n")
    }

    fun name(string: Any) {
        if (identifierChars(lastChar))
            string(" ")
        string(string)
    }

    fun newline() {
        string('\n')
        for (i in 0 until indent) {
            string('\t')
        }
    }

    fun string(string: Any) {
        string(string.toString())
    }

    fun string(string: String) {
        printStream.print(string)
        lastChar = if (string.isNotEmpty()) string.last() else ' '
    }
}
